// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file contains the Genkit flow for suggesting image prompts based on website content.
 *
 * - suggestImagePrompts - A function that takes website content as input and returns suggested image prompts for each section.
 * - SuggestImagePromptsInput - The input type for the suggestImagePrompts function.
 * - SuggestImagePromptsOutput - The return type for the suggestImagePrompts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestImagePromptsInputSchema = z.object({
  websiteContent: z.record(z.string(), z.string()).describe('A record of website sections and their content.'),
});
export type SuggestImagePromptsInput = z.infer<typeof SuggestImagePromptsInputSchema>;

const SuggestImagePromptsOutputSchema = z.record(z.string(), z.string()).describe('A record of website sections and suggested image prompts.');
export type SuggestImagePromptsOutput = z.infer<typeof SuggestImagePromptsOutputSchema>;

export async function suggestImagePrompts(input: SuggestImagePromptsInput): Promise<SuggestImagePromptsOutput> {
  return suggestImagePromptsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestImagePromptsPrompt',
  input: {schema: SuggestImagePromptsInputSchema},
  output: {schema: SuggestImagePromptsOutputSchema},
  prompt: `You are an AI assistant that suggests image prompts for different sections of a website.

  Given the following website content, generate an image prompt for each section that would be suitable for generating an image to visually enhance that section. The output should be a record of website section names and their corresponding image prompts. Be brief and to the point.

  Website Content:
  {{#each websiteContent}}
  Section: {{@key}}
  Content: {{{this}}}
  {{/each}}`,
});

const suggestImagePromptsFlow = ai.defineFlow(
  {
    name: 'suggestImagePromptsFlow',
    inputSchema: SuggestImagePromptsInputSchema,
    outputSchema: SuggestImagePromptsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
